#!/bin/bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

jupyter serverextension enable --sys-prefix --py nbserverproxy 
jupyter serverextension enable --sys-prefix dask_labextension

#EOF
