name: pangeo
channels:
  - conda-forge
dependencies:
  - pandoc
  # core scipy 
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - python-gist
  - fastparquet
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  - pytorch-cpu
  # pyviz
  - hvplot
  - holoviews
  - geoviews
  - panel
  - datashader
  # geospatial
  - iris
  - cartopy
  - geopandas
  - sat-search
  - sat-stac
  - rasterio
  - regionmask
  - rio-cogeo
  - rioxarray
  - netcdf4
  - h5py
  - h5netcdf
  - folium
  # ocean/atmos stuff
  - siphon
  - utide
  - pocean-core
  - owslib
  - ioos-tools
  - geolinks
  - cftime
  - pyoos
  - timeout-decorator
  # geoscience-related
  - climlab
  - metpy
  - satpy
  - gsw
  - eofs
  - esmpy
  - xesmf
  - windspharm
  # intake-related
  - intake>=0.5.4
  - intake-xarray
  - intake-esm
  - intake-stac
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - gcsfs
  - s3fs
  - fsspec
  # jupyter-related
  - ipyleaflet
  # xarray-related
  - xgcm
  - xrft
  - graphviz
  - vim
  - pip
  - pip:
    - git+https://github.com/HDFGroup/h5pyd.git
